# product-service/docker-compose.yml

version: '3.3'
services:
  product-service:
    restart: always
    entrypoint: ["./product-service"]
    container_name: "product-service"
    build: .
    ports:
      - 50051:50051
    links:
      - database
    depends_on:
      - database
    networks:
      - product-service-tier
      - backend-tier
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: mdns

  database:
    image: postgres:latest
    ports:
      - 5434:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - product-service-tier
    environment:
      POSTGRES_PASSWORD: "kevin99123"

networks:
  product-service-tier:
  backend-tier: