// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package com_ta04_srv_product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Picture              string   `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Product) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAllProductsRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllProductsRequest) Reset()         { *m = GetAllProductsRequest{} }
func (m *GetAllProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllProductsRequest) ProtoMessage()    {}
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *GetAllProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllProductsRequest.Unmarshal(m, b)
}
func (m *GetAllProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllProductsRequest.Merge(m, src)
}
func (m *GetAllProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllProductsRequest.Size(m)
}
func (m *GetAllProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllProductsRequest proto.InternalMessageInfo

func (m *GetAllProductsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GetAllProductsRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetOneProductRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneProductRequest) Reset()         { *m = GetOneProductRequest{} }
func (m *GetOneProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneProductRequest) ProtoMessage()    {}
func (*GetOneProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *GetOneProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneProductRequest.Unmarshal(m, b)
}
func (m *GetOneProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneProductRequest.Marshal(b, m, deterministic)
}
func (m *GetOneProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneProductRequest.Merge(m, src)
}
func (m *GetOneProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneProductRequest.Size(m)
}
func (m *GetOneProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneProductRequest proto.InternalMessageInfo

func (m *GetOneProductRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	Product              *Product   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Error                *Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "com.ta04.srv.product.Product")
	proto.RegisterType((*GetAllProductsRequest)(nil), "com.ta04.srv.product.GetAllProductsRequest")
	proto.RegisterType((*GetOneProductRequest)(nil), "com.ta04.srv.product.GetOneProductRequest")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.product.Response")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.product.Error")
}

func init() {
	proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5)
}

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x6f, 0xd2, 0xa6, 0x7f, 0x4e, 0x69, 0xb9, 0x1c, 0x7a, 0x2f, 0xc3, 0xbd, 0x28, 0x21,
	0x0b, 0x29, 0x0a, 0x41, 0xab, 0x22, 0x2e, 0x45, 0x4a, 0x97, 0x4a, 0x8a, 0x4b, 0x91, 0x98, 0x1c,
	0x24, 0xd0, 0x66, 0xd2, 0x99, 0x49, 0xc1, 0x27, 0xf1, 0x39, 0x7c, 0x3d, 0x57, 0x92, 0xc9, 0x44,
	0x5a, 0x8d, 0xda, 0x85, 0xbb, 0x39, 0x39, 0xdf, 0xfc, 0xce, 0x99, 0xef, 0x23, 0xd0, 0xcf, 0x04,
	0x8f, 0xf3, 0x48, 0xf9, 0x99, 0xe0, 0x8a, 0xe3, 0x30, 0xe2, 0x0b, 0x5f, 0x85, 0x87, 0x27, 0xbe,
	0x14, 0x2b, 0xdf, 0xf4, 0xbc, 0x27, 0x0b, 0xda, 0xd7, 0xe5, 0x19, 0x07, 0x60, 0x27, 0x31, 0xb3,
	0x5c, 0x6b, 0xe4, 0x04, 0x76, 0x12, 0x23, 0x42, 0x33, 0x0d, 0x17, 0xc4, 0x6c, 0xd7, 0x1a, 0x75,
	0x03, 0x7d, 0x46, 0x17, 0x7a, 0x31, 0xc9, 0x48, 0x24, 0x99, 0x4a, 0x78, 0xca, 0x1a, 0xba, 0xb5,
	0xfe, 0x09, 0x87, 0xe0, 0x64, 0x22, 0x89, 0x88, 0x35, 0x5d, 0x6b, 0x64, 0x05, 0x65, 0x81, 0x0c,
	0xda, 0x59, 0x12, 0xa9, 0x5c, 0x10, 0x73, 0xf4, 0x9d, 0xaa, 0xc4, 0xbf, 0xd0, 0x92, 0x2a, 0x54,
	0xb9, 0x64, 0x2d, 0xdd, 0x30, 0x95, 0x37, 0x81, 0x3f, 0x53, 0x52, 0x17, 0xf3, 0xb9, 0x59, 0x4f,
	0x06, 0xb4, 0xcc, 0x49, 0xaa, 0x62, 0xc0, 0x32, 0x27, 0xf1, 0xa8, 0x37, 0xed, 0x06, 0x65, 0xb1,
	0x86, 0xb1, 0x37, 0x30, 0x7b, 0x30, 0x9c, 0x92, 0xba, 0x4a, 0xc9, 0x60, 0x2a, 0xca, 0xbb, 0xc7,
	0x7a, 0xcf, 0x16, 0x74, 0x02, 0x92, 0x19, 0x4f, 0x25, 0xe1, 0x19, 0xb4, 0x8d, 0x41, 0x5a, 0xd1,
	0x1b, 0xef, 0xf8, 0x75, 0xee, 0xf9, 0x15, 0xb3, 0x52, 0xe3, 0x11, 0x38, 0x24, 0x04, 0x17, 0x7a,
	0x89, 0xde, 0xf8, 0x7f, 0xfd, 0xb5, 0x49, 0x21, 0x09, 0x4a, 0x25, 0x9e, 0x43, 0xc7, 0x7c, 0x97,
	0xac, 0xe1, 0x36, 0xbe, 0x1f, 0xf6, 0x26, 0xf7, 0x4e, 0xc1, 0xd1, 0xa8, 0x22, 0xa9, 0x88, 0xc7,
	0x64, 0x9e, 0xa3, 0xcf, 0x85, 0xe3, 0x0b, 0x92, 0x32, 0x7c, 0xa8, 0x02, 0xac, 0xca, 0xf1, 0x8b,
	0x0d, 0x03, 0x03, 0x9b, 0x91, 0x58, 0x15, 0xf1, 0xdc, 0xc1, 0x60, 0xd3, 0x6c, 0x3c, 0xa8, 0x5f,
	0xa2, 0x36, 0x92, 0x7f, 0xbb, 0xf5, 0xe2, 0xca, 0x4f, 0xef, 0x17, 0xde, 0x42, 0x7f, 0x23, 0x06,
	0xdc, 0xff, 0x94, 0xff, 0x21, 0xab, 0x2d, 0xf0, 0x33, 0xf8, 0x7d, 0x29, 0x28, 0x54, 0xb4, 0x36,
	0xe1, 0x6b, 0x1b, 0xb7, 0x83, 0xde, 0x64, 0xf1, 0xcf, 0x42, 0xef, 0x5b, 0xfa, 0x6f, 0x3c, 0x7e,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x16, 0x7f, 0x34, 0x92, 0x9e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductServiceClient interface {
	GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...client.CallOption) (*Response, error)
	GetOneProduct(ctx context.Context, in *GetOneProductRequest, opts ...client.CallOption) (*Response, error)
	CreateOneProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	UpdateOneProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
}

type productServiceClient struct {
	c           client.Client
	serviceName string
}

func NewProductServiceClient(serviceName string, c client.Client) ProductServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.ta04.srv.product"
	}
	return &productServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *productServiceClient) GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.GetAllProducts", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetOneProduct(ctx context.Context, in *GetOneProductRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.GetOneProduct", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateOneProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.CreateOneProduct", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateOneProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.UpdateOneProduct", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	GetAllProducts(context.Context, *GetAllProductsRequest, *Response) error
	GetOneProduct(context.Context, *GetOneProductRequest, *Response) error
	CreateOneProduct(context.Context, *Product, *Response) error
	UpdateOneProduct(context.Context, *Product, *Response) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProductService{hdlr}, opts...))
}

type ProductService struct {
	ProductServiceHandler
}

func (h *ProductService) GetAllProducts(ctx context.Context, in *GetAllProductsRequest, out *Response) error {
	return h.ProductServiceHandler.GetAllProducts(ctx, in, out)
}

func (h *ProductService) GetOneProduct(ctx context.Context, in *GetOneProductRequest, out *Response) error {
	return h.ProductServiceHandler.GetOneProduct(ctx, in, out)
}

func (h *ProductService) CreateOneProduct(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.CreateOneProduct(ctx, in, out)
}

func (h *ProductService) UpdateOneProduct(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.UpdateOneProduct(ctx, in, out)
}
